### ISSUE TITLE
input data format

### ISSUE THREAD

**Issue by SeanYXWang** [uxifiit/UXI.GazeToolkit#4]
Hi 

I have a raw gaze data set in csv format, do you have an option to input csv file?

or could you show some examples of the dataset.json, I can convert my csv into json.

Thanks

**Comment by martinkonopka** [comment]
Apologies for late reply. 

The input data format replicates raw gaze data format from Tobii Pro SDK, see the [GazeData](https://github.com/uxifiit/UXI.GazeToolkit/blob/master/src/UXI.GazeToolkit/GazeData.cs) class.
And, currently, only the JSON data format is supported as an input to command line applications.

CSV format is planned but not implemented, as well as converters for raw data output from Tobii Studio or SMI iView/SDK.


Example of a JSON input file with raw gaze data: 
```javascript
[ 
    {
        "TrackerTicks": 1520516784393409,
        "LeftEye": {
            "Validity":"Valid",
            "GazePoint2D": {
                "X": 0.24525205294571606,
                "Y": 0.61409388857714475
            },
            "GazePoint3D": {
                "X": -133.92303374995026,
                "Y": 132.53633104646565,
                "Z": 31.380851961994267
            },
            "EyePosition3D": { 
                "X": -50.04973032434691,
                "Y": 90.771013465694523, 
                "Z": 497.80020319859341
            },
            "EyePosition3DRelative": {
                "X": 0.66211541296593168,
                "Y": 0.149214187440748, 
                "Z": 0.15933400471999448
            },
            "PupilDiameter": 4.32537841796875
        },
        "RightEye": {
            // same structure as in LeftEye    
        },
        "Timestamp":"15:18:29.0976878"
    },
    // other samples...
]
```

* `TrackerTicks` (long) - time when the data was sampled by the Eye Tracker in *microseconds* from arbitrary point in time. 
* `Timestamp` (time) - time when the data was received from or sampled by the Eye Tracker. `TrackerTicks` field is used for filtering, `Timestamp` is optional.
* `Validity` code for each eye may be of these values: `Invalid`, `Valid`, `Probably`, `Unknown`
* `GazePoint2D` - gaze point on the display area, relative to its size.
* `GazePoint3D` - target gaze point of the eye on the display area, starting in the center of the eye tracker surface area.
* `EyePosition3D` - position of the eye in 3D space, starting in the center of the eye tracker surface area.
* `EyePosition3DRelative` - same position as in `EyePosition3DRelative` but relative to the trackbox

**Comment by martinkonopka** [comment]
#10  #9 are open to solve this issue in the project.
#7 added CSV data format.

**Comment by martinkonopka** [comment]
Support for CSV was finally completed in 1cd0b5ffc9418517c15dedb4bb7d89d1b35203f6

Example CSV raw gaze data:
```CSV
Timestamp,LeftValidity,LeftGazePoint2DX,LeftGazePoint2DY,LeftGazePoint3DX,LeftGazePoint3DY,LeftGazePoint3DZ,LeftEyePosition3DX,LeftEyePosition3DY,LeftEyePosition3DZ,LeftPupilDiameter,RightValidity,RightGazePoint2DX,RightGazePoint2DY,RightGazePoint3DX,RightGazePoint3DY,RightGazePoint3DZ,RightEyePosition3DX,RightEyePosition3DY,RightEyePosition3DZ,RightPupilDiameter
2019-02-20T14:30:19.6025869+01:00,Valid,0.489926785230637,0.555088818073273,-4.44773054122925,149.954650878906,37.7207260131836,-39.9742164611816,8.12003993988037,660.34716796875,3.09280395507813,Valid,0.481412410736084,0.568204283714294,-8.89732265472412,145.926071166992,36.2544441223145,23.385913848877,3.26203179359436,658.651123046875,3.17863464355469
...
```

Eye movements in CSV format:

```CSV
Timestamp,MovementType,Duration,AverageGazePoint2DX,AverageGazePoint2DY,AverageGazePoint3DX,AverageGazePoint3DY,AverageGazePoint3DZ,AverageEyePosition3DX,AverageEyePosition3DY,AverageEyePosition3DZ,AveragePupilDiameter
2019-02-20T14:30:19.8609674+01:00,Fixation,82.78,0.249512461496861,0.37049186064908,-130.087534517832,206.655870400095,58.3583148675617,-10.1834323612157,6.58115161135798,660.914666037136,3.19873046875
...
```
